<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<name>Buession Springcloud Parent</name>
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.buession</groupId>
		<artifactId>parent</artifactId>
		<relativePath/>
		<version>4.0.1</version>
	</parent>
	<groupId>com.buession.springcloud</groupId>
	<artifactId>buession-springcloud-parent</artifactId>
	<url>https://springcloud.buession.com/</url>
	<description>Buession SpringCloud Framework Parent</description>
	<version>4.0.1</version>
	<packaging>pom</packaging>

	<organization>
		<name>buession.com Inc.</name>
		<url>http://www.buession.com/</url>
	</organization>

	<developers>
		<developer>
			<id>yong.teng</id>
			<name>yong.teng</name>
			<email>webmaster@buession.com</email>
			<roles>
				<role>Project Manager</role>
				<role>Developer</role>
			</roles>
		</developer>
	</developers>

	<licenses>
		<license>
			<name>The Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
			<comments>A business-friendly OSS license</comments>
		</license>
	</licenses>

	<scm>
		<connection>scm:git:https://github.com/buession/buession-springcloud.git</connection>
		<developerConnection>scm:git:https://github.com/buession/buession-springcloud.git</developerConnection>
		<url>https://github.com/buession/buession-springcloud</url>
	</scm>

	<issueManagement>
		<system>github</system>
		<url>https://github.com/buession/buession-springcloud/issues</url>
	</issueManagement>

	<modules>
		<module>../buession-springcloud-common</module>
		<module>../buession-springcloud-bus</module>
		<module>../buession-springcloud-config-client</module>
		<module>../buession-springcloud-config-server</module>
		<module>../buession-springcloud-consul</module>
		<module>../buession-springcloud-feign</module>
		<module>../buession-springcloud-gateway</module>
		<module>../buession-springcloud-kubernetes</module>
		<module>../buession-springcloud-loadbalancer</module>
		<module>../buession-springcloud-metrics</module>
		<module>../buession-springcloud-nacos-config-client</module>
		<module>../buession-springcloud-nacos-discovery</module>
		<module>../buession-springcloud-sleuth</module>
	</modules>

	<properties>
		<buession.version>4.0.0</buession.version>
		<buession.springboot.version>4.0.0</buession.springboot.version>
		<springcloud.version>4.3.0</springcloud.version>
		<alibaba.cloud.nacos.version>2025.0.0.0</alibaba.cloud.nacos.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.buession.springboot</groupId>
				<artifactId>buession-springboot-boot</artifactId>
				<version>${buession.springboot.version}</version>
				<exclusions>
					<exclusion>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-starter-actuator</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>com.buession.springboot</groupId>
				<artifactId>buession-springboot-web</artifactId>
				<version>${buession.springboot.version}</version>
			</dependency>

			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-stream</artifactId>
				<version>${springcloud.version}</version>
				<exclusions>
					<exclusion>
						<groupId>org.springframework.cloud</groupId>
						<artifactId>spring-cloud-starter</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.springframework.boot</groupId>
						<artifactId>*</artifactId>
					</exclusion>
					<exclusion>
						<groupId>javax.annotation</groupId>
						<artifactId>javax.annotation-api</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jetbrains.kotlin</groupId>
						<artifactId>kotlin-stdlib-jdk8</artifactId>
					</exclusion>
				</exclusions>
			</dependency>

			<dependency>
				<groupId>com.fasterxml.jackson.datatype</groupId>
				<artifactId>jackson-datatype-joda</artifactId>
				<version>${fasterxml.jackson.datatype.version}</version>
				<exclusions>
					<exclusion>
						<groupId>joda-time</groupId>
						<artifactId>joda-time</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<finalName>buession-springcloud-parent</finalName>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<includes>
					<include>**/*.*</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.sonatype.central</groupId>
				<artifactId>central-publishing-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>